module.exports = {
    'webCtl': require('./webCtl'),
    'crawlCtl': require('./crawlCtl'),
    'articleCtl': require('./articleCtl'),
    'sectionCtl': require('./sectionCtl'),
    'userCtl': require('./userCtl'),
    'queueCtl': require('./queueCtl'),
    'dashboardCtl': require('./dashboardCtl'),
    'mediaCtl': require('./mediaCtl'),
    'linkCtl': require('./linkCtl'),
    'articleTestCtl': require('./articleTestCtl'),
    'globalLinkCtl': require('./globalLinkCtl'),
    'rawWebsiteCtl': require('./rawWebsiteCtl'),
    'keywordLinkCtl': require('./keywordLinkCtl'),
    'sectionLogCtl': require('./sectionLogCtl'),
    'sectionLinkCtl': require('./sectionLinkCtl'),
    'articleStageCtl': require('./articleStageCtl'),
    'crawlerDashboard': require('./crawler'),
    'potchInstanceCtl': require('./potchIntanceCtl'),
    'markAnalyzerCtl': require('./markAnalyzerCtl'),
    'linkClassifierCtl': require('./linkClassifierCtl'),
    'linkTaggerCtl': require('./linkTaggerCtl'),
    'mapperCtl': require('./mapperCtl'),
}