module.exports = {
    'websites': require('./websiteBp'),
    'articles': require('./articleBp'),
    'sections': require('./sectionBp'),
    'queues': require('./queueBp'),
    'links': require('./linkBp'),
    'article_tests': require('./articleTestBp'),
    'global_links': require('./globalLinkBp'),
    'raw_websites': require('./rawWebsiteBp'),
    'keyword_links': require('./keywordLink'),
    'section_logs': require('./sectionLogBp'),
    'section_links': require('./sectionLinkBp'),
    'article_stages': require('./articleStageBp'),
    'potch_instances': require('./potchInstanceBp'),
    'mark_analyzers': require('./markAnalyzerBp'),
    'link_classifiers': require('./linkClassifierBp'),
    'link_taggers': require('./linkTaggerBp'),
    'mappers': require('./mapperBp'),
    'raw_urls': require('./rawUrlBp'),
    'redis_articles': require('./redisArticleBp')
}